### ISSUE TITLE
Toggles ignore disable

### ISSUE THREAD

**Issue by TeraMika** [stfc-aeg/odin-react#2]
If you give a toggle switch a disable tag, it won't do anything with it.

See [ToggleSwitch.jsx](https://github.com/stfc-aeg/odin-react/blob/master/src/components/ToggleSwitch.jsx), it accepts disabled as a prop but does not use it. This means that toggle switches cannot be disabled.

**Comment by TeraMika** [comment]
Testing further, dropdowns also cannot be disabled, as they do not even accept disabled as a prop. Is this something that's possible and also desirable?

**Comment by ANeaves** [comment]
For dropdowns, I think a good behaviour to aim for would be to keep the button itself enabled, but disable the menu options within the dropdown itself. That way, even if it's disabled, the user can still see what options SHOULD be available once the dropdown is re-enabled

**Comment by TeraMika** [comment]
That's a good point and a good suggestion, agreed with that
