### ISSUE TITLE
Providing disable removes disable-on-put behaviour

### ISSUE THREAD

**Issue by TeraMika** [stfc-aeg/odin-react#3]
By default, components disable briefly when a put is made. However, when disable's properties are manually defined in a component this behaviour is overridden.

[withEndpoint.js](https://github.com/stfc-aeg/odin-react/blob/master/src/services/withEndpoint.js) contains the behaviour. Disable is accepted and used if provided, but the disable-on-put is used only if no disable behaviour is manually provided.

I believe this should work more like an `OR` so that the disable-on-put can be used alongside other disable logic without specifying this manually.

**Comment by ANeaves** [comment]
Fixed a while ago, forgot to close issue
